default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: d96qd4jb8hno97
  username: xnpihizungrzoi
  host: ec2-107-22-122-106.compute-1.amazonaws.com
  password: 5e11bb5f6074ad55cb2615d78a4e9bb80e727ab171e1c1b8235219ef1fe1d8e4

